# Generated by Django 5.0.2 on 2024-02-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerComplaints',
            fields=[
                ('reporting_date', models.DateField(verbose_name='reporting_date')),
                ('complaint_code', models.CharField(max_length=7, verbose_name='complaint_code')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=5, verbose_name='gender')),
                ('frequency', models.CharField(max_length=10, verbose_name='frequency')),
                ('complainant_name', models.CharField(max_length=25, verbose_name='complainant_name')),
                ('complainant_age', models.PositiveSmallIntegerField(verbose_name='complainant_age')),
                ('complainant_contact_number', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='complainant_contact_number')),
                ('location', models.CharField(max_length=10, verbose_name='location')),
                ('education_level', models.CharField(choices=[('P', 'Primary'), ('S', 'Secondary'), ('T', 'Tertiary'), ('U', 'University'), ('C', 'College')], max_length=10, verbose_name='education_level')),
                ('extra_details', models.CharField(max_length=255, verbose_name='extra_details')),
                ('agent_id', models.CharField(max_length=10, verbose_name='agent_id')),
                ('date_of_occurence', models.DateField(verbose_name='date_of_occurence')),
                ('report_date', models.DateField(verbose_name='report_date')),
                ('date_resolved', models.DateField(verbose_name='date_resolved')),
                ('remedial_status', models.CharField(max_length=15, verbose_name='remedial_status')),
                ('amount_lost', models.PositiveBigIntegerField(verbose_name='amount_lost')),
                ('amount_recovered', models.PositiveBigIntegerField(verbose_name='amount_recovered')),
            ],
            options={
                'unique_together': {('reporting_date', 'complaint_code', 'frequency', 'complainant_name')},
            },
        ),
    ]
