# Generated by Django 5.0.2 on 2024-02-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_remove_customercomplaints_report_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercomplaints',
            name='amount_lost',
            field=models.BigIntegerField(choices=[('K', 'Ksh'), ('U', 'USh'), ('T', 'TZs')], verbose_name='amount_lost'),
        ),
        migrations.AlterField(
            model_name='customercomplaints',
            name='amount_recovered',
            field=models.BigIntegerField(choices=[('K', 'Ksh'), ('U', 'USh'), ('T', 'TZs')], verbose_name='amount_recovered'),
        ),
    ]
