# Generated by Django 5.0.2 on 2024-02-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_alter_customercomplaints_amount_lost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercomplaints',
            name='amount_lost',
        ),
        migrations.RemoveField(
            model_name='customercomplaints',
            name='amount_recovered',
        ),
        migrations.AddField(
            model_name='customercomplaints',
            name='amount',
            field=models.BigIntegerField(default='0000', verbose_name='amount'),
        ),
        migrations.AddField(
            model_name='customercomplaints',
            name='currency',
            field=models.CharField(choices=[('K', 'Ksh'), ('U', 'USh'), ('T', 'TZs')], default='0000', max_length=1, verbose_name='currency'),
        ),
    ]
