# Generated by Django 5.0.2 on 2024-02-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_remove_customercomplaints_amount_lost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercomplaints',
            name='psp_id',
            field=models.CharField(max_length=10, null=True, verbose_name='psp_id'),
        ),
        migrations.AddField(
            model_name='customercomplaints',
            name='row_id',
            field=models.IntegerField(null=True, verbose_name='row_id'),
        ),
    ]
