# Generated by Django 5.0.2 on 2024-02-22 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_customercomplaints_psp_id_customercomplaints_row_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercomplaints',
            name='amount',
            field=models.BigIntegerField(default='0', verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='customercomplaints',
            name='currency',
            field=models.CharField(choices=[('K', 'Ksh'), ('U', 'USh'), ('T', 'TZs')], default='0', max_length=1, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='customercomplaints',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('C', 'Coporate')], max_length=5, verbose_name='gender'),
        ),
        migrations.CreateModel(
            name='ScheduledDirectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField(null=True, verbose_name='row_id')),
                ('psp_id', models.CharField(max_length=10, null=True, verbose_name='psp_id')),
                ('reporting_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='reporting_date')),
                ('directors_name', models.CharField(max_length=255, verbose_name='directors_name')),
                ('gender', models.CharField(max_length=10, verbose_name='gender')),
                ('type_of_director', models.CharField(choices=[('E', 'Executive'), ('N', 'Non-Executive')], max_length=10, verbose_name='type_of_director')),
                ('date_of_birth', models.DateField(verbose_name='date_of_birth')),
                ('identification_documents', models.CharField(choices=[('I', 'ID'), ('P', 'Passport')], max_length=20, verbose_name='identifictaion_documents')),
                ('level_of_education', models.CharField(choices=[('P', 'PHD'), ('M', 'MBA'), ('B', 'BSE')], max_length=255, verbose_name='level_of_education')),
                ('directorship_position', models.CharField(max_length=255, verbose_name='directorship_position')),
                ('contact_number', models.CharField(max_length=20, verbose_name='contact_number')),
                ('appointment_date', models.DateField(verbose_name='appointment_date')),
                ('retirement_date', models.DateField(max_length=255, verbose_name='retirement_date')),
                ('data_transparency', models.CharField(max_length=255, verbose_name='data_transparency')),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('end_date', models.DateField(verbose_name='end_date')),
                ('pin', models.CharField(max_length=20, verbose_name='pin')),
            ],
            options={
                'unique_together': {('pin', 'identification_documents')},
            },
        ),
    ]
