# Generated by Django 5.0.2 on 2024-02-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0006_alter_customercomplaints_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleddirectors',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('C', 'Coporate')], max_length=5, verbose_name='gender'),
        ),
    ]
