# Generated by Django 5.0.2 on 2024-02-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0007_alter_scheduleddirectors_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercomplaints',
            name='remedial_status',
        ),
        migrations.AddField(
            model_name='customercomplaints',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete')], max_length=15, null=True, verbose_name='remedial_status'),
        ),
    ]
