# Generated by Django 5.0.2 on 2024-02-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0008_remove_customercomplaints_remedial_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercomplaints',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete')], max_length=15, null=True, verbose_name='status'),
        ),
    ]
