# Generated by Django 5.0.2 on 2024-02-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0011_alter_customercomplaints_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractmodel',
            name='complaints',
            field=models.CharField(default=1, max_length=255, verbose_name='complaints'),
        ),
    ]
